### ISSUE TITLE
Have you released any of the classes in CocoaPods?

### ISSUE THREAD

**Issue by jhowardjr** [schneiderandre/popping#18]
In development we've been playing around with your PaperButton class and would like to include it in our project.

**Comment by schneiderandre** [comment]
Hey @jhowardjr, thanks for your interest :smile:. I didn't release this one as an own framework, but maybe I'll revisit it sometime, rewrite it in Swift and polish the API. But to be honest, I can`t promise anything.

Have a great day! André
